import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent, type ReactNode } from "react";
import {
  AlertTriangle, ArrowDownToLine, BarChart3, Bell, CalendarDays, Camera, Car, Check,
  ChevronRight, CircleDollarSign, Clock3, Copy, Download, Eye, EyeOff, GraduationCap,
  Home, LoaderCircle, LogOut, MapPin, Moon, Navigation, Pencil, Phone, Plus, QrCode,
  ReceiptText, RefreshCw, Search, ShieldCheck, Sparkles, Star, Sun, Trash2, UserRound,
  Users, WalletCards, X,
} from "lucide-react";
import { toast } from "sonner";
import { useUniCarona } from "@/hooks/use-unicarona";
import { campuses, initialState, type Ride, type RideRequest, type RideStatus, type User, type View } from "@/lib/unicarona-data";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Progress } from "@/components/ui/progress";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

const universityOptions = ["PUC Minas Coração Eucarístico", "PUC Minas Praça da Liberdade", "UFMG Pampulha", "CEFET-MG Nova Suíça", "PUC Minas Barreiro"];
const glass = "glass-card rounded-3xl";
const fieldClass = "h-12 rounded-full border-border/70 bg-background/60 px-4 shadow-none";

type ConfirmKind = "logout" | "delete" | "cancel" | "reject" | null;
type ModalKind = "driver" | "request" | "wallet" | "receipt" | "edit-profile" | "edit-ride" | "passenger" | "notifications" | "pix" | null;

function initials(name: string) { return name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase(); }
function maskPhone(value: string) { const digits = value.replace(/\D/g, "").slice(0, 11); return digits.replace(/^(\d{2})(\d)/, "($1) $2").replace(/(\d{5})(\d)/, "$1-$2"); }
function academicEmail(email: string) { return /^[^\s@]+@(?:[\w-]+\.)*(?:edu\.br|pucminas\.br|ufmg\.br|cefetmg\.br)$/i.test(email); }

function UserAvatar({ user, className = "size-11" }: { user: User; className?: string }) {
  return <Avatar className={`${className} ring-2 ring-background`}><AvatarImage src={user.photo} alt={`Foto de ${user.name}`} /><AvatarFallback className="bg-primary/15 font-bold text-primary">{user.avatar || initials(user.name)}</AvatarFallback></Avatar>;
}

function Field({ label, error, valid, children }: { label: string; error?: string; valid?: boolean; children: ReactNode }) {
  return <div className="space-y-2"><div className="flex items-center justify-between px-1"><Label className="text-sm font-semibold">{label}</Label>{valid && <span className="animate-in fade-in flex items-center gap-1 text-xs font-bold text-success"><Check className="size-3.5" /> E-mail verificado</span>}</div>{children}{error && <p className="animate-in slide-in-from-top-1 flex items-center gap-1.5 px-2 text-xs font-medium text-destructive"><AlertTriangle className="size-3.5 shrink-0" />{error}</p>}</div>;
}

function PasswordInput({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) {
  const [visible, setVisible] = useState(false);
  return <div className="relative"><Input className={`${fieldClass} pr-12`} type={visible ? "text" : "password"} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /><Button type="button" variant="ghost" size="icon" className="absolute right-1 top-1 size-10 rounded-full" onClick={() => setVisible((current) => !current)} aria-label={visible ? "Ocultar senha" : "Mostrar senha"}>{visible ? <EyeOff /> : <Eye />}</Button></div>;
}

function Status({ value }: { value: RideStatus | "Recusada" | "Confirmada" }) {
  const style = value === "Aprovada" || value === "Confirmada" ? "bg-success-soft text-success" : value === "Em andamento" ? "bg-live text-live-foreground" : value === "Cancelada" || value === "Recusada" ? "bg-destructive/10 text-destructive" : value === "Concluída" ? "bg-muted text-muted-foreground" : "bg-warning-soft text-warning";
  return <Badge className={`${style} rounded-full border-0 px-3 py-1 text-[11px] shadow-none`}>{value}</Badge>;
}

function Login({ onLogin, onSignup }: { onLogin: (email: string, password: string) => boolean; onSignup: (user: User) => void }) {
  const [signup, setSignup] = useState(false);
  const [email, setEmail] = useState("bruno.andrade@pucminas.br");
  const [password, setPassword] = useState("unicarona123");
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [university, setUniversity] = useState(universityOptions[0]);
  const [photo, setPhoto] = useState<string>();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const validEmail = academicEmail(email);
  const strength = password.length >= 12 ? 3 : password.length >= 8 ? 2 : password.length ? 1 : 0;
  const upload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setPhoto(typeof reader.result === "string" ? reader.result : undefined); reader.readAsDataURL(file); };
  const submit = (event: FormEvent) => {
    event.preventDefault(); setError("");
    if (!validEmail) { setError("Use seu e-mail institucional da universidade para continuar."); toast.error("Confira o e-mail acadêmico informado."); return; }
    if (signup && (!name.trim() || phone.length < 15 || password.length < 8)) { setError("Preencha seu nome, telefone completo e uma senha com pelo menos 8 caracteres."); toast.error("Alguns dados obrigatórios precisam de atenção."); return; }
    setBusy(true);
    window.setTimeout(() => {
      if (signup) onSignup({ id: `u-${Date.now()}`, name: name.trim(), email, password, university, phone, photo, bio: "Novo membro da comunidade UniCarona.", course: "Estudante", avatar: initials(name), rating: 5, completedRides: 0, type: "passageira", walletConfigured: false });
      else if (!onLogin(email, password)) { setError("E-mail ou senha não conferem. Tente novamente."); toast.error("Não foi possível entrar com esses dados."); }
      setBusy(false);
    }, 550);
  };
  return <main className="min-h-screen bg-app px-4 py-8 text-foreground sm:grid sm:place-items-center">
    <section className="glass-card mx-auto w-full max-w-md rounded-[2rem] p-6 shadow-device sm:p-8">
      <div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-primary"><Car /></span><div><b className="text-xl">UniCarona</b><p className="text-xs text-muted-foreground">Mobilidade universitária</p></div></div><Badge className="rounded-full bg-success-soft text-success"><ShieldCheck /> Seguro</Badge></div>
      <div className="mb-7"><p className="text-sm font-bold text-primary">{signup ? "Sua jornada começa aqui" : "Que bom ter você de volta"}</p><h1 className="mt-2 text-3xl font-extrabold tracking-normal">{signup ? "Crie sua conta" : "Entre na UniCarona"}</h1><p className="mt-2 text-sm text-muted-foreground">Uma comunidade verificada para compartilhar caminhos em Belo Horizonte.</p></div>
      <form onSubmit={submit} className="space-y-5">
        {signup && <><div className="flex justify-center"><label className="group relative cursor-pointer"><Avatar className="size-24 border-4 border-background shadow-lg"><AvatarImage src={photo} alt="Prévia da foto de perfil" /><AvatarFallback className="bg-secondary text-xl font-bold text-primary">{name ? initials(name) : <UserRound />}</AvatarFallback></Avatar><span className="absolute bottom-0 right-0 grid size-8 place-items-center rounded-full bg-primary text-primary-foreground shadow-md"><Camera className="size-4" /></span><input className="sr-only" type="file" accept="image/*" onChange={upload} /><span className="sr-only">Selecionar foto de perfil</span></label></div><Field label="Nome completo"><Input className={fieldClass} value={name} onChange={(event) => setName(event.target.value)} placeholder="Como aparece na universidade" /></Field><Field label="Universidade"><Select value={university} onValueChange={setUniversity}><SelectTrigger className={fieldClass}><SelectValue /></SelectTrigger><SelectContent>{universityOptions.map((option) => <SelectItem value={option} key={option}>{option}</SelectItem>)}</SelectContent></Select></Field><Field label="Telefone"><Input className={fieldClass} value={phone} onChange={(event) => setPhone(maskPhone(event.target.value))} placeholder="(31) 99999-9999" /></Field></>}
        <Field label="E-mail acadêmico" valid={validEmail} error={email && !validEmail ? "Informe um e-mail institucional, como nome@ufmg.br." : undefined}><Input className={fieldClass} type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="seu.nome@universidade.edu.br" /></Field>
        <Field label="Senha"><PasswordInput value={password} onChange={setPassword} placeholder="Mínimo de 8 caracteres" />{signup && <div className="flex items-center gap-2 px-2"><div className="grid flex-1 grid-cols-3 gap-1">{[1, 2, 3].map((step) => <span key={step} className={`h-1.5 rounded-full ${strength >= step ? step === 1 ? "bg-destructive" : step === 2 ? "bg-warning" : "bg-success" : "bg-muted"}`} />)}</div><span className="text-[11px] text-muted-foreground">{strength === 3 ? "Forte" : strength === 2 ? "Boa" : "Fraca"}</span></div>}</Field>
        {error && <div className="rounded-2xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
        <Button className="h-12 w-full rounded-full bg-primary-gradient font-bold shadow-primary" disabled={busy}>{busy ? <LoaderCircle className="animate-spin" /> : signup ? "Criar minha conta" : "Entrar"}</Button>
      </form>
      <Button variant="ghost" className="mt-4 w-full rounded-full text-primary" onClick={() => { setSignup((current) => !current); setError(""); }}>{signup ? "Já tenho uma conta" : "Criar uma conta acadêmica"}</Button>
      {!signup && <p className="mt-4 rounded-2xl bg-muted/70 p-3 text-center text-xs text-muted-foreground">Para a demonstração, use Bruno ou Camila com a senha <b>unicarona123</b>.</p>}
    </section>
  </main>;
}

const passengerMenu: { id: View; label: string; icon: typeof Home }[] = [
  { id: "inicio", label: "Início", icon: Home }, { id: "buscar", label: "Buscar", icon: Search }, { id: "corrida", label: "Viagens", icon: Navigation }, { id: "painel", label: "Resumo", icon: BarChart3 }, { id: "perfil", label: "Perfil", icon: UserRound },
];
const driverMenu: { id: View; label: string; icon: typeof Home }[] = [
  { id: "inicio", label: "Início", icon: Home }, { id: "publicar", label: "Oferecer", icon: Plus }, { id: "solicitacoes", label: "Pedidos", icon: Users }, { id: "painel", label: "Resumo", icon: BarChart3 }, { id: "perfil", label: "Perfil", icon: UserRound },
];

export function UniCaronaApp() {
  const { state, update, reset, hydrated } = useUniCarona();
  const [view, setView] = useState<View>("inicio");
  const [modal, setModal] = useState<ModalKind>(null);
  const [confirm, setConfirm] = useState<ConfirmKind>(null);
  const [selectedRideId, setSelectedRideId] = useState("r3");
  const [selectedRequestId, setSelectedRequestId] = useState("q1");
  const current = state.users.find((user) => user.id === state.currentUserId) ?? null;
  const selectedRide = state.rides.find((ride) => ride.id === selectedRideId);
  const selectedDriver = state.users.find((user) => user.id === selectedRide?.driverId);
  const selectedRequest = state.requests.find((request) => request.id === selectedRequestId);
  const selectedPassenger = state.users.find((user) => user.id === selectedRequest?.passengerId);
  const setState = (patch: Partial<typeof state>) => update((previous) => ({ ...previous, ...patch }));
  const notify = (userId: string, text: string) => update((previous) => ({ ...previous, notifications: [{ id: `n-${Date.now()}`, userId, text, read: false, time: "Agora" }, ...previous.notifications] }));
  const switchPersona = (id: "bruno" | "camila") => { setState({ currentUserId: id }); setView("inicio"); toast.success(`Modo alterado para ${id === "bruno" ? "Bruno, motorista" : "Camila, passageira"}.`); };
  const login = (email: string, password: string) => { const user = state.users.find((item) => item.email.toLowerCase() === email.toLowerCase() && item.password === password); if (!user) return false; setState({ currentUserId: user.id }); toast.success(`Bem-vindo, ${user.name.split(" ")[0]}!`); return true; };
  const signup = (user: User) => { update((previous) => ({ ...previous, users: [...previous.users, user], currentUserId: user.id })); toast.success("Conta criada e e-mail acadêmico verificado!"); };
  if (!hydrated) return <div className="grid min-h-screen place-items-center bg-app"><LoaderCircle className="size-8 animate-spin text-primary" /><span className="sr-only">Carregando UniCarona</span></div>;
  if (!current) return <Login onLogin={login} onSignup={signup} />;

  const isDriver = current.type === "motorista";
  const menu = isDriver ? driverMenu : passengerMenu;
  const unread = state.notifications.filter((item) => item.userId === current.id && !item.read).length;
  const approve = (id: string) => { const request = state.requests.find((item) => item.id === id); update((previous) => ({ ...previous, requests: previous.requests.map((item) => item.id === id ? { ...item, status: "Aprovada" } : item), rides: previous.rides.map((ride) => ride.id === request?.rideId ? { ...ride, seats: Math.max(0, ride.seats - 1) } : ride) })); if (request) notify(request.passengerId, "Sua vaga foi aprovada. Finalize o PIX em até 15 minutos."); toast.success("Vaga aprovada e passageira notificada!"); };
  const requestRide = () => { if (!selectedRide) return; if (state.requests.some((item) => item.rideId === selectedRide.id && item.passengerId === current.id)) { toast.error("Você já solicitou essa carona."); setModal(null); return; } update((previous) => ({ ...previous, requests: [...previous.requests, { id: `q-${Date.now()}`, rideId: selectedRide.id, passengerId: current.id, status: "Pendente", createdAt: "Agora" }] })); notify(selectedRide.driverId, `${current.name} solicitou uma vaga.`); toast.success("Solicitação enviada ao motorista!"); setModal("pix"); };

  return <TooltipProvider><div className="min-h-screen bg-app px-0 py-0 text-foreground sm:px-5 sm:py-6">
    <div className="phone-shell mx-auto flex min-h-[100dvh] w-full max-w-md flex-col overflow-hidden bg-surface shadow-device sm:min-h-[calc(100dvh-3rem)] sm:rounded-[2.5rem] sm:border sm:border-white/30">
      <header className="glass-header sticky top-0 z-30 flex items-center gap-3 px-5 pb-3 pt-4"><div className="min-w-0 flex-1"><p className="text-xs font-medium text-muted-foreground">Olá, {current.name.split(" ")[0]}!</p><h1 className="truncate text-lg font-extrabold tracking-normal">{isDriver ? "Pronto para dirigir?" : "Para onde vamos hoje?"}</h1></div><Button variant="ghost" size="icon" className="relative rounded-full" onClick={() => { setModal("notifications"); update((previous) => ({ ...previous, notifications: previous.notifications.map((item) => item.userId === current.id ? { ...item, read: true } : item) })); }} aria-label="Abrir notificações"><Bell />{unread > 0 && <span className="absolute right-1 top-1 size-2.5 rounded-full bg-destructive ring-2 ring-background" />}</Button><UserAvatar user={current} />
      </header>
      <main className="flex-1 overflow-y-auto px-4 pb-28 pt-4">
        {view === "inicio" && <HomeView user={current} rides={state.rides} requests={state.requests} users={state.users} go={setView} onRide={(id) => { setSelectedRideId(id); setModal("driver"); }} />}
        {view === "buscar" && <SearchView rides={state.rides.filter((ride) => ride.driverId !== current.id)} users={state.users} onProfile={(id) => { setSelectedRideId(id); setModal("driver"); }} onRequest={(id) => { setSelectedRideId(id); setModal("request"); }} />}
        {view === "publicar" && <PublishView user={current} rides={state.rides} onWallet={() => setModal("wallet")} onCreate={(ride) => { update((previous) => ({ ...previous, rides: [ride, ...previous.rides] })); toast.success("Carona publicada com sucesso!"); setView("inicio"); }} onEdit={(id) => { setSelectedRideId(id); setModal("edit-ride"); }} onCancel={(id) => { setSelectedRideId(id); setConfirm("cancel"); }} />}
        {view === "solicitacoes" && <RequestsView requests={state.requests} rides={state.rides} users={state.users} driverId={current.id} onProfile={(id) => { setSelectedRequestId(id); setModal("passenger"); }} onApprove={approve} onReject={(id) => { setSelectedRequestId(id); setConfirm("reject"); }} />}
        {view === "corrida" && <TrackingView onFinish={() => { toast.success("Viagem concluída. Obrigado por compartilhar o caminho!"); setView("painel"); }} />}
        {view === "painel" && <DashboardView user={current} onReceipt={() => setModal("receipt")} />}
        {view === "perfil" && <ProfileView user={current} theme={state.theme} onTheme={(dark) => setState({ theme: dark ? "dark" : "light" })} onEdit={() => setModal("edit-profile")} onWallet={() => setModal("wallet")} onSwitch={switchPersona} onReset={() => { reset(); toast.success("Dados da demonstração restaurados."); }} onLogout={() => setConfirm("logout")} onDelete={() => setConfirm("delete")} />}
      </main>
      <nav className="glass-dock fixed bottom-4 left-1/2 z-40 grid w-[calc(100%-2rem)] max-w-[25rem] -translate-x-1/2 grid-cols-5 rounded-full p-1.5 shadow-2xl">{menu.map(({ id, label, icon: Icon }) => <Button key={id} variant="ghost" onClick={() => setView(id)} className={`h-14 min-w-0 flex-col gap-1 rounded-full px-1 text-[10px] ${view === id ? "bg-primary-gradient text-primary-foreground shadow-primary hover:text-primary-foreground" : "text-muted-foreground"}`}><Icon className="size-5" /><span className="truncate">{label}</span></Button>)}</nav>
    </div>
    <ProfileDialog open={modal === "edit-profile"} user={current} onClose={() => setModal(null)} onSave={(values) => { update((previous) => ({ ...previous, users: previous.users.map((user) => user.id === current.id ? { ...user, ...values, avatar: initials(values.name ?? user.name) } : user) })); setModal(null); toast.success("Perfil atualizado com sucesso!"); }} />
    <PersonDialog open={modal === "driver" || modal === "passenger"} person={modal === "driver" ? selectedDriver : selectedPassenger} title={modal === "driver" ? "Perfil do motorista" : "Perfil da passageira"} onClose={() => setModal(null)} />
    <RequestDialog open={modal === "request"} ride={selectedRide} driver={selectedDriver} onClose={() => setModal(null)} onConfirm={requestRide} />
    <PixDialog open={modal === "pix"} onClose={() => setModal(null)} />
    <WalletDialog open={modal === "wallet"} onClose={() => setModal(null)} onConfirm={() => { update((previous) => ({ ...previous, users: previous.users.map((user) => user.id === current.id ? { ...user, walletConfigured: true } : user) })); setModal(null); toast.success("Chave PIX configurada com sucesso!"); }} />
    <ReceiptDialog open={modal === "receipt"} user={current} onClose={() => setModal(null)} />
    <EditRideDialog open={modal === "edit-ride"} ride={selectedRide} onClose={() => setModal(null)} onSave={(ride) => { update((previous) => ({ ...previous, rides: previous.rides.map((item) => item.id === ride.id ? ride : item) })); setModal(null); toast.success("Carona atualizada. O preço continua fixo em R$ 6,00."); }} />
    <NotificationsDialog open={modal === "notifications"} notifications={state.notifications.filter((item) => item.userId === current.id)} onClose={() => setModal(null)} />
    <ConfirmationDialog kind={confirm} onClose={() => setConfirm(null)} onConfirm={() => { if (confirm === "logout") setState({ currentUserId: null }); if (confirm === "delete") update((previous) => ({ ...initialState, users: previous.users.filter((user) => user.id !== current.id), currentUserId: null, theme: previous.theme })); if (confirm === "cancel") update((previous) => ({ ...previous, rides: previous.rides.map((ride) => ride.id === selectedRideId ? { ...ride, status: "Cancelada" } : ride) })); if (confirm === "reject") update((previous) => ({ ...previous, requests: previous.requests.map((request) => request.id === selectedRequestId ? { ...request, status: "Recusada" } : request) })); toast.success(confirm === "logout" ? "Sessão encerrada com segurança." : confirm === "delete" ? "Conta excluída." : confirm === "cancel" ? "Carona cancelada e passageiros avisados." : "Solicitação recusada."); setConfirm(null); }} />
  </div></TooltipProvider>;
}

function SectionTitle({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="mb-4 flex items-end justify-between gap-3"><div><h2 className="text-xl font-extrabold tracking-normal">{title}</h2>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div>{action}</div>; }
function Metric({ icon: Icon, value, label, tint = "primary" }: { icon: typeof Car; value: string; label: string; tint?: "primary" | "blue" | "lime" }) { const color = tint === "blue" ? "bg-sky-soft text-sky" : tint === "lime" ? "bg-live text-live-foreground" : "bg-primary/12 text-primary"; return <div className={`${glass} p-4`}><span className={`grid size-9 place-items-center rounded-2xl ${color}`}><Icon className="size-4" /></span><b className="mt-5 block text-xl">{value}</b><span className="mt-1 block text-xs leading-tight text-muted-foreground">{label}</span></div>; }

function HomeView({ user, rides, requests, users, go, onRide }: { user: User; rides: Ride[]; requests: RideRequest[]; users: User[]; go: (view: View) => void; onRide: (id: string) => void }) {
  const driver = user.type === "motorista";
  const available = rides.filter((ride) => ride.driverId !== user.id && ride.status === "Pendente").slice(0, 2);
  const pending = requests.filter((request) => request.status === "Pendente" && rides.some((ride) => ride.id === request.rideId && ride.driverId === user.id)).length;
  return <div className="space-y-6">
    <section className="hero-card relative overflow-hidden rounded-3xl p-5 text-primary-foreground shadow-primary"><div className="relative z-10"><Badge className="rounded-full bg-live text-live-foreground">{driver ? `${pending} pedido${pending === 1 ? "" : "s"} aguardando` : "Carona confirmada"}</Badge><h2 className="mt-7 max-w-[16rem] text-2xl font-extrabold tracking-normal">{driver ? "Sua próxima saída está quase completa" : "Seu motorista chega em 8 minutos"}</h2><p className="mt-2 max-w-[17rem] text-sm text-primary-foreground/75">Gameleira → PUC Minas<br />Hoje, 07:20</p><Button variant="secondary" className="mt-5 rounded-full" onClick={() => go(driver ? "solicitacoes" : "corrida")}>{driver ? "Ver solicitações" : "Acompanhar ao vivo"}<ChevronRight /></Button></div><Car className="absolute -bottom-6 -right-7 size-40 rotate-[-8deg] text-primary-foreground/10" /></section>
    {!driver && <section><SectionTitle title="Acesso rápido" /><div className="grid grid-cols-3 gap-3">{[{ icon: Search, label: "Buscar carona", view: "buscar" as View }, { icon: Navigation, label: "Minhas viagens", view: "corrida" as View }, { icon: ReceiptText, label: "Comprovantes", view: "painel" as View }].map(({ icon: Icon, label, view }) => <Button key={label} variant="ghost" className={`${glass} h-28 flex-col gap-3 px-2 text-xs font-bold`} onClick={() => go(view)}><span className="grid size-10 place-items-center rounded-2xl bg-secondary text-primary"><Icon /></span>{label}</Button>)}</div></section>}
    {driver && <div className="grid grid-cols-2 gap-3"><Metric icon={CircleDollarSign} value="R$ 420,00" label="Arrecadado neste mês" tint="lime" /><Metric icon={Users} value="78" label="Passageiros transportados" tint="blue" /></div>}
    <section><SectionTitle title={driver ? "Suas caronas" : "Caronas disponíveis"} description={driver ? "Acompanhe as próximas saídas" : "Rotas escolhidas para você"} action={<Button variant="ghost" className="rounded-full px-3 text-primary" onClick={() => go(driver ? "publicar" : "buscar")}>Ver todas</Button>} /><div className="space-y-3">{(driver ? rides.filter((ride) => ride.driverId === user.id && ride.status === "Pendente") : available).map((ride) => { const person = users.find((item) => item.id === ride.driverId); return <RideCard key={ride.id} ride={ride} driver={person} onProfile={() => onRide(ride.id)} onAction={() => go(driver ? "publicar" : "buscar")} own={driver} />; })}</div></section>
  </div>;
}

function RideCard({ ride, driver, onProfile, onAction, own = false }: { ride: Ride; driver?: User; onProfile: () => void; onAction: () => void; own?: boolean }) {
  return <article className={`${glass} p-4`}><div className="flex items-center gap-3">{driver && <Button variant="ghost" size="icon" className="size-11 rounded-full p-0" onClick={onProfile}><UserAvatar user={driver} /></Button>}<div className="min-w-0 flex-1"><b className="block truncate text-sm">{driver?.name ?? "Sua carona"}</b><p className="flex items-center gap-1 text-xs text-muted-foreground"><Star className="size-3 fill-warning text-warning" /> {ride.rating.toFixed(1)} · {ride.vehicle}</p></div><Status value={ride.status} /></div><div className="route-line my-5 space-y-4 pl-7"><div><span className="text-[11px] text-muted-foreground">Origem</span><p className="text-sm font-semibold">{ride.origin}</p></div><div><span className="text-[11px] text-muted-foreground">Destino</span><p className="text-sm font-semibold">{ride.destination}</p></div></div><div className="flex items-center gap-3 border-t border-border/60 pt-3 text-xs text-muted-foreground"><span className="flex items-center gap-1"><Clock3 className="size-3.5" />{ride.time}</span><span className="flex items-center gap-1"><Users className="size-3.5" />{ride.seats} vagas</span><b className="ml-auto text-base text-foreground">R$ 6,00</b><Button variant="ghost" size="icon" className="size-8 rounded-full" onClick={onAction} aria-label={own ? "Gerenciar carona" : "Ver carona"}><ChevronRight /></Button></div></article>;
}

function SearchView({ rides, users, onProfile, onRequest }: { rides: Ride[]; users: User[]; onProfile: (id: string) => void; onRequest: (id: string) => void }) {
  const [origin, setOrigin] = useState("Estação Gameleira"); const [destination, setDestination] = useState("PUC Minas - Campus Coração Eucarístico"); const [date, setDate] = useState("2026-09-16"); const [searching, setSearching] = useState(false); const [searched, setSearched] = useState(false);
  const visible = useMemo(() => rides.filter((ride) => ride.status === "Pendente"), [rides]);
  return <div><SectionTitle title="Buscar carona" description="Encontre horários que combinam com sua rotina." /><section className={`${glass} mb-6 space-y-4 p-4`}><Field label="De onde você sai?"><Input className={fieldClass} list="campuses" value={origin} onChange={(event) => setOrigin(event.target.value)} /></Field><Field label="Para onde você vai?"><Input className={fieldClass} list="campuses" value={destination} onChange={(event) => setDestination(event.target.value)} /></Field><Field label="Quando?"><Input className={fieldClass} type="date" value={date} onChange={(event) => setDate(event.target.value)} /></Field><datalist id="campuses">{campuses.map((campus) => <option value={campus} key={campus} />)}</datalist><Button className="h-12 w-full rounded-full bg-primary-gradient shadow-primary" onClick={() => { setSearching(true); window.setTimeout(() => { setSearching(false); setSearched(true); toast.success("Encontramos as melhores caronas para você."); }, 550); }}>{searching ? <LoaderCircle className="animate-spin" /> : <Search />}{searching ? "Buscando..." : "Buscar caronas"}</Button></section><SectionTitle title={searched ? `${visible.length} opções encontradas` : "Disponíveis perto de você"} /><div className="space-y-3">{visible.map((ride) => <RideCard key={ride.id} ride={ride} driver={users.find((user) => user.id === ride.driverId)} onProfile={() => onProfile(ride.id)} onAction={() => onRequest(ride.id)} />)}</div></div>;
}

function PublishView({ user, rides, onWallet, onCreate, onEdit, onCancel }: { user: User; rides: Ride[]; onWallet: () => void; onCreate: (ride: Ride) => void; onEdit: (id: string) => void; onCancel: (id: string) => void }) {
  const [origin, setOrigin] = useState("Estação Gameleira"); const [destination, setDestination] = useState("PUC Minas - Campus Coração Eucarístico"); const [date, setDate] = useState("2026-09-17"); const [time, setTime] = useState("07:20"); const [seats, setSeats] = useState("2"); const [plate, setPlate] = useState(user.vehicle?.plate ?? ""); const [vehicle, setVehicle] = useState(user.vehicle?.model ?? "");
  const submit = (event: FormEvent) => { event.preventDefault(); if (!user.walletConfigured) { onWallet(); return; } if (!origin || !destination || !date || !time || !vehicle || !/^[A-Z]{3}\d[A-Z]\d{2}$/.test(plate)) { toast.error("Revise os campos e informe uma placa válida, como ABC1D23."); return; } onCreate({ id: `r-${Date.now()}`, driverId: user.id, origin, destination, date, time, seats: Number(seats), status: "Pendente", vehicle, plate, rating: user.rating }); };
  const own = rides.filter((ride) => ride.driverId === user.id && ride.status === "Pendente");
  return <div className="space-y-7"><div><SectionTitle title="Oferecer carona" description="Compartilhe seu trajeto com estudantes verificados." /><form onSubmit={submit} className={`${glass} space-y-4 p-4`}>
    {!user.walletConfigured && <div className="rounded-2xl bg-warning-soft p-4 text-warning"><div className="flex gap-3"><WalletCards className="shrink-0" /><div><b className="text-sm">Configure sua chave PIX de recebimento</b><p className="mt-1 text-xs">Ela é necessária antes de publicar caronas.</p><Button type="button" size="sm" className="mt-3 rounded-full" onClick={onWallet}>Configurar em 1 clique</Button></div></div></div>}
    <Field label="Origem"><Input className={fieldClass} list="campuses" value={origin} onChange={(event) => setOrigin(event.target.value)} /></Field><Field label="Destino"><Input className={fieldClass} list="campuses" value={destination} onChange={(event) => setDestination(event.target.value)} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Data"><Input className={fieldClass} type="date" value={date} onChange={(event) => setDate(event.target.value)} /></Field><Field label="Horário"><Input className={fieldClass} type="time" value={time} onChange={(event) => setTime(event.target.value)} /></Field></div><Field label="Vagas"><div className="grid grid-cols-4 gap-2">{[1, 2, 3, 4].map((amount) => <Button type="button" variant={seats === String(amount) ? "default" : "outline"} className="rounded-full" key={amount} onClick={() => setSeats(String(amount))}>{amount}</Button>)}</div></Field><Field label="Modelo do carro"><Input className={fieldClass} value={vehicle} onChange={(event) => setVehicle(event.target.value)} placeholder="Chevrolet Onix 2022" /></Field><Field label="Placa Mercosul"><Input className={fieldClass} value={plate} onChange={(event) => setPlate(event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 7))} placeholder="ABC1D23" /></Field>
    <div className="rounded-2xl bg-secondary/70 p-4 text-sm"><div className="flex justify-between"><span>Tarifa fixa</span><b>R$ 5,25</b></div><div className="mt-2 flex justify-between"><span>Taxa de serviço</span><b>R$ 0,75</b></div><div className="mt-3 flex items-center justify-between border-t border-border/60 pt-3"><span className="font-bold">Total do passageiro</span><span className="flex items-center gap-2"><b className="text-lg text-primary">R$ 6,00</b><Tooltip><TooltipTrigger asChild><Button type="button" variant="ghost" size="icon" className="size-7 rounded-full"><CircleDollarSign className="size-4" /></Button></TooltipTrigger><TooltipContent>O preço é padronizado e não pode ser alterado.</TooltipContent></Tooltip></span></div></div><Button className="h-12 w-full rounded-full bg-primary-gradient shadow-primary"><Plus />Publicar carona</Button>
  </form></div><section><SectionTitle title="Caronas publicadas" description="Edite horários ou cancele uma saída." /><div className="space-y-3">{own.map((ride) => <article key={ride.id} className={`${glass} p-4`}><div className="flex justify-between"><div><b className="text-sm">{ride.origin}</b><p className="mt-1 text-xs text-muted-foreground">até {ride.destination}</p></div><Status value={ride.status} /></div><div className="mt-4 flex items-center gap-2"><span className="mr-auto text-sm font-bold">{ride.time} · {ride.seats} vagas</span><Button variant="outline" size="icon" className="rounded-full" onClick={() => onEdit(ride.id)} aria-label="Editar carona"><Pencil /></Button><Button variant="destructive" size="icon" className="rounded-full" onClick={() => onCancel(ride.id)} aria-label="Cancelar carona"><X /></Button></div></article>)}</div></section></div>;
}

function RequestsView({ requests, rides, users, driverId, onProfile, onApprove, onReject }: { requests: RideRequest[]; rides: Ride[]; users: User[]; driverId: string; onProfile: (id: string) => void; onApprove: (id: string) => void; onReject: (id: string) => void }) {
  const relevant = requests.filter((request) => rides.some((ride) => ride.id === request.rideId && ride.driverId === driverId));
  return <div><SectionTitle title="Central de solicitações" description="Conheça cada estudante antes de confirmar a vaga." />{relevant.length ? <div className="space-y-3">{relevant.map((request) => { const passenger = users.find((user) => user.id === request.passengerId); const ride = rides.find((item) => item.id === request.rideId); if (!passenger || !ride) return null; return <article key={request.id} className={`${glass} p-4`}><Button variant="ghost" className="h-auto w-full justify-start gap-3 rounded-2xl p-0 text-left" onClick={() => onProfile(request.id)}><UserAvatar user={passenger} className="size-12" /><div className="min-w-0 flex-1"><b className="block truncate">{passenger.name}</b><p className="mt-1 truncate text-xs text-muted-foreground">{passenger.course} · ★ {passenger.rating}</p></div><ChevronRight /></Button><div className="my-4 rounded-2xl bg-muted/70 p-3 text-xs"><b>{ride.time}</b><p className="mt-1 truncate text-muted-foreground">{ride.origin} → {ride.destination}</p></div><div className="flex items-center gap-2"><Status value={request.status} />{request.status === "Pendente" && <><Button variant="outline" className="ml-auto rounded-full" onClick={() => onReject(request.id)}>Recusar</Button><Button className="rounded-full" onClick={() => onApprove(request.id)}><Check />Aprovar vaga</Button></>}</div></article>; })}</div> : <EmptyState icon={Users} title="Nenhum pedido por enquanto" text="Quando alguém solicitar uma vaga, você verá aqui." />}</div>;
}

function TrackingView({ onFinish }: { onFinish: () => void }) {
  const [progress, setProgress] = useState(48);
  return <div><SectionTitle title="Acompanhamento ao vivo" description="Seu embarque está próximo." /><section className="relative min-h-[620px] overflow-hidden rounded-3xl bg-map shadow-xl"><svg viewBox="0 0 430 640" className="absolute inset-0 h-full w-full" role="img" aria-label="Mapa ilustrado do trajeto em Belo Horizonte"><path d="M-20 95 C90 40 140 155 240 100 S360 25 470 90 M-10 315 C120 260 195 370 450 250 M40 560 C150 470 255 585 460 470 M70 -30 C115 120 50 265 135 690 M330 -20 C280 160 390 315 310 690" className="stroke-map-road" fill="none" strokeWidth="18" /><path d="M70 530 C140 445 120 350 230 315 S250 180 355 115" className="route-glow stroke-primary" fill="none" strokeLinecap="round" strokeWidth="7" /><circle cx="70" cy="530" r="9" className="fill-success" /><circle cx="355" cy="115" r="9" className="fill-primary" /><g className="car-marker" transform={`translate(${70 + progress * 2.85} ${530 - progress * 4.15})`}><circle r="23" className="fill-primary/20 animate-ping" /><circle r="17" className="fill-primary" /><path d="M-8 3h16l-2-9H-5z" className="fill-primary-foreground" /></g></svg><div className="absolute left-4 right-4 top-4 flex items-center gap-3 rounded-full bg-live px-4 py-3 text-live-foreground shadow-lg"><span className="size-2.5 animate-pulse rounded-full bg-live-foreground" /><b className="text-sm">A 8 min do ponto de embarque</b></div><div className="glass-card absolute inset-x-3 bottom-3 rounded-3xl p-4"><div className="flex items-center gap-3"><Avatar className="size-12"><AvatarFallback className="bg-primary/15 font-bold text-primary">MC</AvatarFallback></Avatar><div className="min-w-0 flex-1"><b className="block">Marina Costa</b><p className="text-xs text-muted-foreground">Hyundai HB20 2023 · Cinza</p><p className="mt-1 text-xs font-bold">RTO2A65 · ★ 5,0</p></div><Button variant="destructive" size="icon" className="rounded-full" onClick={() => toast.error("Contato de emergência acionado na simulação.")} aria-label="Acionar emergência"><Phone /></Button></div><div className="mt-4"><div className="mb-2 flex justify-between text-xs"><span>Progresso do trajeto</span><b>{progress}%</b></div><Progress value={progress} className="h-2" /></div><Button className="mt-4 h-11 w-full rounded-full" onClick={() => { setProgress(100); window.setTimeout(onFinish, 450); }}><Check />Simular chegada</Button></div></section></div>;
}

function DashboardView({ user, onReceipt }: { user: User; onReceipt: () => void }) {
  const driver = user.type === "motorista"; const bars = [36, 62, 48, 82, 100, 44, 24];
  return <div><SectionTitle title={driver ? "Resumo do motorista" : "Resumo da passageira"} description="Seu impacto na mobilidade universitária." /><section className={`${glass} mb-4 grid place-items-center p-6 text-center`}><div className="gauge relative grid size-44 place-items-center rounded-full"><div className="grid size-32 place-items-center rounded-full bg-card"><div>{driver ? <Car className="mx-auto mb-2 text-primary" /> : <Sparkles className="mx-auto mb-2 text-primary" />}<b className="block text-2xl">{driver ? "R$ 420,00" : "R$ 195,00"}</b><span className="mt-1 block max-w-24 text-xs text-muted-foreground">{driver ? "total arrecadado" : "economia estimada no mês"}</span></div></div></div></section><div className="grid grid-cols-3 gap-2"><Metric icon={Car} value={driver ? "32" : "16"} label={driver ? "Caronas oferecidas" : "Caronas realizadas"} /><Metric icon={driver ? Users : CircleDollarSign} value={driver ? "78" : "R$ 96"} label={driver ? "Passageiros" : "Total investido"} tint="blue" /><Metric icon={Star} value={driver ? "4,9" : "5,0"} label="Nota média" tint="lime" /></div>{driver && <section className={`${glass} mt-4 p-4`}><div className="flex items-center justify-between"><b>Caronas por dia</b><Badge variant="secondary" className="rounded-full">Esta semana</Badge></div><div className="mt-6 flex h-36 items-end gap-2">{bars.map((height, index) => <div key={index} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="bar-fill rounded-full" style={{ height: `${height}%` }} /><span className="text-center text-[10px] text-muted-foreground">{["S", "T", "Q", "Q", "S", "S", "D"][index]}</span></div>)}</div></section>}<section className={`${glass} mt-4 p-4`}><b>Viagens recentes</b>{["PUC Minas → Praça da Liberdade", "Gameleira → Coração Eucarístico", "UFMG → Centro de BH"].map((route, index) => <div key={route} className="flex items-center gap-3 border-b border-border/50 py-4 last:border-0"><span className="grid size-9 place-items-center rounded-2xl bg-success-soft text-success"><Check /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{route}</p><p className="text-xs text-muted-foreground">{12 - index * 3} set · R$ 6,00</p></div><Button variant="ghost" size="icon" className="rounded-full" onClick={onReceipt} aria-label="Ver comprovante"><ReceiptText /></Button></div>)}</section></div>;
}

function ProfileView({ user, theme, onTheme, onEdit, onWallet, onSwitch, onReset, onLogout, onDelete }: { user: User; theme: "light" | "dark"; onTheme: (dark: boolean) => void; onEdit: () => void; onWallet: () => void; onSwitch: (id: "bruno" | "camila") => void; onReset: () => void; onLogout: () => void; onDelete: () => void }) {
  return <div className="space-y-4"><SectionTitle title="Meu perfil" description="Sua identidade na comunidade UniCarona." /><section className={`${glass} p-5 text-center`}><UserAvatar user={user} className="mx-auto size-24" /><h2 className="mt-4 text-xl font-extrabold">{user.name}</h2><p className="mt-1 text-sm text-muted-foreground">{user.course} · {user.university}</p><Badge className="mt-3 rounded-full bg-success-soft text-success"><ShieldCheck />Estudante verificado</Badge><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-muted/70 p-3"><b>{user.rating} ★</b><p className="text-xs text-muted-foreground">Avaliação</p></div><div className="rounded-2xl bg-muted/70 p-3"><b>{user.completedRides}</b><p className="text-xs text-muted-foreground">Caronas concluídas</p></div></div><Button variant="outline" className="mt-4 w-full rounded-full" onClick={onEdit}><Pencil />Editar perfil</Button></section>
    <section className={`${glass} p-4`}><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-secondary text-primary">{theme === "dark" ? <Moon /> : <Sun />}</span><div className="flex-1"><b className="text-sm">Aparência</b><p className="text-xs text-muted-foreground">{theme === "dark" ? "Tema escuro" : "Tema claro"}</p></div><Switch checked={theme === "dark"} onCheckedChange={onTheme} aria-label="Alternar tema escuro" /></div></section>
    <section className={`${glass} p-4`}><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-sky-soft text-sky"><WalletCards /></span><div className="flex-1"><b className="text-sm">Recebimentos PIX</b><p className="text-xs text-muted-foreground">{user.walletConfigured ? "Chave configurada" : "Configuração pendente"}</p></div><Button variant="ghost" size="icon" className="rounded-full" onClick={onWallet}><ChevronRight /></Button></div></section>
    <section className={`${glass} p-4`}><div className="mb-4"><p className="text-xs font-bold uppercase text-primary">Modo de demonstração</p><h3 className="mt-1 font-bold">Escolha uma perspectiva</h3><p className="mt-1 text-xs text-muted-foreground">Veja os fluxos dedicados de motorista e passageira.</p></div><div className="rounded-full bg-muted p-1"><div className="grid grid-cols-2 gap-1"><Button variant="ghost" className={`h-14 rounded-full text-xs ${user.id === "bruno" ? "bg-card text-primary shadow-sm" : "text-muted-foreground"}`} onClick={() => onSwitch("bruno")}><Car />Bruno<br />Motorista</Button><Button variant="ghost" className={`h-14 rounded-full text-xs ${user.id === "camila" ? "bg-card text-primary shadow-sm" : "text-muted-foreground"}`} onClick={() => onSwitch("camila")}><UserRound />Camila<br />Passageira</Button></div></div><Button variant="ghost" className="mt-3 w-full rounded-full text-xs text-muted-foreground" onClick={onReset}><RefreshCw />Restaurar dados da demonstração</Button></section>
    <section className={`${glass} space-y-2 p-3`}><Button variant="ghost" className="w-full justify-start rounded-2xl" onClick={onLogout}><LogOut />Sair da conta</Button><Button variant="ghost" className="w-full justify-start rounded-2xl text-destructive hover:text-destructive" onClick={onDelete}><Trash2 />Excluir conta</Button></section>
  </div>;
}

function EmptyState({ icon: Icon, title, text }: { icon: typeof Users; title: string; text: string }) { return <div className={`${glass} grid place-items-center px-6 py-12 text-center`}><span className="grid size-14 place-items-center rounded-3xl bg-muted text-muted-foreground"><Icon /></span><h3 className="mt-4 font-bold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{text}</p></div>; }
function dialogClass() { return "glass-dialog max-w-[calc(100%-2rem)] rounded-3xl border-white/30 sm:max-w-md"; }

function PersonDialog({ open, person, title, onClose }: { open: boolean; person?: User; title: string; onClose: () => void }) { return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent className={dialogClass()}>{person && <><DialogHeader><div className="flex items-center gap-4"><UserAvatar user={person} className="size-16" /><div><DialogTitle>{person.name}</DialogTitle><DialogDescription>{person.course} · {person.university}</DialogDescription></div></div></DialogHeader><Badge className="w-fit rounded-full bg-success-soft text-success"><ShieldCheck />Perfil acadêmico verificado</Badge><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-muted/70 p-3 text-center"><b>{person.rating} ★</b><p className="text-xs text-muted-foreground">Avaliação</p></div><div className="rounded-2xl bg-muted/70 p-3 text-center"><b>{person.completedRides}</b><p className="text-xs text-muted-foreground">Caronas</p></div></div>{person.vehicle && <div className="rounded-2xl border border-border/70 p-4"><b className="text-sm">Veículo</b><p className="mt-1 text-sm text-muted-foreground">{person.vehicle.model} · {person.vehicle.color} · {person.vehicle.plate}</p></div>}<div><b className="text-sm">Avaliação de colega</b><blockquote className="mt-2 rounded-2xl bg-muted/70 p-3 text-sm">“Pontual, gentil e muito cuidadoso no trajeto.”<span className="mt-1 block text-xs text-muted-foreground">Estudante da UFMG</span></blockquote></div></>}</DialogContent></Dialog>; }

function RequestDialog({ open, ride, driver, onClose, onConfirm }: { open: boolean; ride?: Ride; driver?: User; onClose: () => void; onConfirm: () => void }) { return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent className={dialogClass()}><DialogHeader><DialogTitle>Solicitar esta vaga?</DialogTitle><DialogDescription>Confira os detalhes antes de enviar seu pedido.</DialogDescription></DialogHeader>{ride && <div className="space-y-3 rounded-2xl bg-muted/70 p-4 text-sm"><p><b>Motorista:</b> {driver?.name}</p><p><b>Saída:</b> {ride.origin}</p><p><b>Destino:</b> {ride.destination}</p><p><b>Embarque:</b> {ride.date.split("-").reverse().join("/")} às {ride.time}</p><div className="flex justify-between border-t border-border/60 pt-3 text-base"><b>Total</b><b className="text-primary">R$ 6,00</b></div></div>}<DialogFooter><Button variant="outline" className="rounded-full" onClick={onClose}>Agora não</Button><Button className="rounded-full" onClick={onConfirm}>Confirmar pedido</Button></DialogFooter></DialogContent></Dialog>; }

function PixDialog({ open, onClose }: { open: boolean; onClose: () => void }) { const [seconds, setSeconds] = useState(15 * 60); useEffect(() => { if (!open) return; setSeconds(15 * 60); const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [open]); const minutes = String(Math.floor(seconds / 60)).padStart(2, "0"); const rest = String(seconds % 60).padStart(2, "0"); return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent className={dialogClass()}><DialogHeader><DialogTitle>Pagamento PIX reservado</DialogTitle><DialogDescription>Sua vaga fica reservada por 15 minutos.</DialogDescription></DialogHeader><div className="text-center"><Badge className="rounded-full bg-live text-live-foreground"><Clock3 />{minutes}:{rest}</Badge><div className="qr-mock mx-auto my-5 grid size-44 place-items-center rounded-3xl bg-foreground p-3 text-background"><QrCode className="size-36" /></div><b className="text-2xl">R$ 6,00</b><p className="mt-1 text-sm text-muted-foreground">Pagamento simulado com confirmação imediata.</p></div><Button className="h-12 w-full rounded-full" onClick={() => toast.success("Código PIX copiado!")}><Copy />Copiar código PIX</Button><Button variant="ghost" className="rounded-full" onClick={onClose}>Pagar depois</Button></DialogContent></Dialog>; }

function WalletDialog({ open, onClose, onConfirm }: { open: boolean; onClose: () => void; onConfirm: () => void }) { return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent className={dialogClass()}><DialogHeader><DialogTitle>Configure sua chave PIX</DialogTitle><DialogDescription>Receba automaticamente após cada carona concluída.</DialogDescription></DialogHeader><div className="rounded-3xl bg-primary/10 p-6 text-center"><WalletCards className="mx-auto size-12 text-primary" /><b className="mt-3 block">Chave por e-mail</b><p className="mt-1 text-sm text-muted-foreground">Nenhum dado bancário real será usado nesta simulação.</p></div><DialogFooter><Button variant="outline" className="rounded-full" onClick={onClose}>Agora não</Button><Button className="rounded-full" onClick={onConfirm}><ShieldCheck />Configurar em 1 clique</Button></DialogFooter></DialogContent></Dialog>; }

function ProfileDialog({ open, user, onClose, onSave }: { open: boolean; user: User; onClose: () => void; onSave: (values: Partial<User>) => void }) { const [name, setName] = useState(user.name); const [phone, setPhone] = useState(user.phone); const [bio, setBio] = useState(user.bio); const [photo, setPhoto] = useState(user.photo); useEffect(() => { if (open) { setName(user.name); setPhone(user.phone); setBio(user.bio); setPhoto(user.photo); } }, [open, user]); const upload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setPhoto(typeof reader.result === "string" ? reader.result : undefined); reader.readAsDataURL(file); }; return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent className={dialogClass()}><DialogHeader><DialogTitle>Editar perfil</DialogTitle><DialogDescription>Atualize os dados visíveis para outros estudantes.</DialogDescription></DialogHeader><label className="mx-auto cursor-pointer text-center"><Avatar className="mx-auto size-20"><AvatarImage src={photo} /><AvatarFallback>{initials(name)}</AvatarFallback></Avatar><span className="mt-2 flex items-center gap-1 text-xs font-bold text-primary"><Camera className="size-3" />Alterar foto</span><input type="file" accept="image/*" className="sr-only" onChange={upload} /></label><Field label="Nome completo"><Input className={fieldClass} value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Telefone"><Input className={fieldClass} value={phone} onChange={(event) => setPhone(maskPhone(event.target.value))} /></Field><Field label="Sobre você"><Textarea className="min-h-24 rounded-3xl bg-background/60" value={bio} onChange={(event) => setBio(event.target.value)} /></Field><DialogFooter><Button variant="outline" className="rounded-full" onClick={onClose}>Cancelar</Button><Button className="rounded-full" onClick={() => { if (!name.trim() || phone.length < 15) { toast.error("Informe nome e telefone completos."); return; } onSave({ name: name.trim(), phone, bio, photo }); }}>Salvar alterações</Button></DialogFooter></DialogContent></Dialog>; }

function EditRideDialog({ open, ride, onClose, onSave }: { open: boolean; ride?: Ride; onClose: () => void; onSave: (ride: Ride) => void }) { const [time, setTime] = useState(ride?.time ?? "07:20"); const [seats, setSeats] = useState(String(ride?.seats ?? 2)); useEffect(() => { if (open && ride) { setTime(ride.time); setSeats(String(ride.seats)); } }, [open, ride]); return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent className={dialogClass()}><DialogHeader><DialogTitle>Editar carona</DialogTitle><DialogDescription>Altere horário e vagas. O valor permanece fixo.</DialogDescription></DialogHeader><Field label="Horário"><Input className={fieldClass} type="time" value={time} onChange={(event) => setTime(event.target.value)} /></Field><Field label="Vagas"><Select value={seats} onValueChange={setSeats}><SelectTrigger className={fieldClass}><SelectValue /></SelectTrigger><SelectContent>{[1, 2, 3, 4].map((amount) => <SelectItem key={amount} value={String(amount)}>{amount} {amount === 1 ? "vaga" : "vagas"}</SelectItem>)}</SelectContent></Select></Field><div className="rounded-2xl bg-muted p-3 text-sm"><span>Total por passageiro</span><b className="float-right text-primary">R$ 6,00</b></div><DialogFooter><Button variant="outline" className="rounded-full" onClick={onClose}>Cancelar</Button><Button className="rounded-full" onClick={() => ride && onSave({ ...ride, time, seats: Number(seats) })}>Salvar carona</Button></DialogFooter></DialogContent></Dialog>; }

function ReceiptDialog({ open, user, onClose }: { open: boolean; user: User; onClose: () => void }) { return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent className={dialogClass()}><DialogHeader><DialogTitle>Comprovante da carona</DialogTitle><DialogDescription>Viagem concluída em 12 de setembro de 2026.</DialogDescription></DialogHeader><div className="space-y-3 rounded-2xl border border-border/70 p-4 text-sm"><div className="flex justify-between"><span>Estudante</span><b>{user.name}</b></div><div className="flex justify-between"><span>Trajeto</span><b>Gameleira → PUC</b></div><div className="flex justify-between"><span>Tarifa fixa</span><b>R$ 5,25</b></div><div className="flex justify-between"><span>Taxa de serviço</span><b>R$ 0,75</b></div><div className="flex justify-between border-t border-border/60 pt-3 text-base"><b>Total pago</b><b className="text-primary">R$ 6,00</b></div></div><Button className="w-full rounded-full" onClick={() => toast.success("Comprovante salvo na simulação.")}><Download />Baixar comprovante</Button></DialogContent></Dialog>; }

function NotificationsDialog({ open, notifications, onClose }: { open: boolean; notifications: { id: string; text: string; time: string }[]; onClose: () => void }) { return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent className={dialogClass()}><DialogHeader><DialogTitle>Notificações</DialogTitle><DialogDescription>Atualizações sobre suas caronas.</DialogDescription></DialogHeader><div className="space-y-2">{notifications.length ? notifications.map((item) => <div key={item.id} className="flex gap-3 rounded-2xl bg-muted/70 p-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-primary/15 text-primary"><Bell className="size-4" /></span><div><p className="text-sm font-medium">{item.text}</p><p className="mt-1 text-xs text-muted-foreground">{item.time}</p></div></div>) : <p className="py-8 text-center text-sm text-muted-foreground">Você está em dia por aqui.</p>}</div></DialogContent></Dialog>; }

function ConfirmationDialog({ kind, onClose, onConfirm }: { kind: ConfirmKind; onClose: () => void; onConfirm: () => void }) { const content = kind === "delete" ? ["Excluir conta definitivamente?", "Esta ação é irreversível e apagará seu perfil e histórico neste navegador.", "Excluir minha conta"] : kind === "cancel" ? ["Cancelar esta carona?", "Os passageiros confirmados serão avisados e receberão o reembolso automaticamente.", "Cancelar carona"] : kind === "reject" ? ["Recusar esta solicitação?", "A passageira será avisada e poderá procurar outra opção de trajeto.", "Recusar solicitação"] : ["Deseja sair da sua conta?", "Seus dados continuarão salvos com segurança neste navegador.", "Sair da conta"]; return <AlertDialog open={kind !== null} onOpenChange={(value) => !value && onClose()}><AlertDialogContent className={dialogClass()}><AlertDialogHeader><div className={`mb-2 grid size-12 place-items-center rounded-2xl ${kind === "logout" ? "bg-primary/10 text-primary" : "bg-destructive/10 text-destructive"}`}>{kind === "logout" ? <LogOut /> : <AlertTriangle />}</div><AlertDialogTitle>{content[0]}</AlertDialogTitle><AlertDialogDescription>{content[1]}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel className="rounded-full">Voltar</AlertDialogCancel><AlertDialogAction className={`rounded-full ${kind === "logout" ? "" : "bg-destructive text-destructive-foreground hover:bg-destructive/90"}`} onClick={onConfirm}>{content[2]}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }
